apiVersion: v1
kind: Namespace
metadata:
  name: flash-cards
  labels:
    app: flash-cards

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistentvolumeclaim
  namespace: flash-cards
  labels:
    app: mongodb
spec:
  securityContext:
    fsGroup: 502
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: flash-cards
  labels:
    name: mongodb
spec:
  securityContext:
    fsGroup: 502
  type: ClusterIP
  ports:
    - port: 27017
  selector:
    name: mongodb

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-access-client
  namespace: flash-cards
  labels:
    name: mongodb
spec:
  securityContext:
    fsGroup: 502
  type: NodePort
  ports:
    - port: 27017
  selector:
    name: mongodb

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  namespace: flash-cards
  labels:
    app: mongodb
spec:
  securityContext:
    fsGroup: 502
  serviceName: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
       name: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.3
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_DATA_DIR
              value: "/data/db"
            - name: MONGO_LOG_DIR
              value: "/dev/null"
          volumeMounts:
            - name: mongodb-volume
              mountPath: /data/db
      volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: mongodb-persistentvolumeclaim

---

apiVersion: v1
kind: Service
metadata:
  name: flash-cards-service
  namespace: flash-cards
  labels:
    app: flash-cards
spec:
  securityContext:
    fsGroup: 502
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 8080
      name: http
  selector:
    name: flash-cards

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flash-cards-deployment
  namespace: flash-cards
  labels:
    app: flash-cards
spec:
  securityContext:
    fsGroup: 502
  replicas: 1
  template:
    metadata:
      labels:
        name: flash-cards
    spec:
      containers:
        - name: flash-cards
          image: dogood/flash-cards:latest
          ports:
            - containerPort: 8080

