apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistentvolumeclaim
  namespace: flash-cards
  labels:
    app: mongodb
spec:
  securityContext:
    fsGroup: 500
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi