apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-access-client
  namespace: flash-cards
  labels:
    name: mongodb
spec:
  securityContext:
    fsGroup: 500
  type: NodePort
  ports:
    - port: 27017
  selector:
    name: mongodb