apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  namespace: flash-cards
  labels:
    app: mongodb
spec:
  securityContext:
    fsGroup: 500
  serviceName: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
       name: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.3
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_DATA_DIR
              value: "/data/db"
            - name: MONGO_LOG_DIR
              value: "/dev/null"
          volumeMounts:
            - name: mongodb-volume
              mountPath: /data/db
      volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: mongodb-persistentvolumeclaim